### PR TITLE
Working towards libreadsb

### PR DESCRIPTION
**Pull request by afk11**
I was trying to call some functions from this project from a go application and ran into some issues. The functions I'm interested in are pretty much just `decodeModeAMessage` and `decodeModeSMessage`. Then I just want to probe the modesMessage structure that's returned.

Issues I ran into:
 - main() is defined in readsb, so collides with my apps main
 - lots of small files include readsb.h, which includes everything. so put relevant dependencies in each c file.
 - some of the useful functions are static (airground_to_string, and all of those)
 - `Modes` global variable

This PR is still WIP, but I think it's a start towards separating library code from the application code. Now that things are decoupled from readsb.h, it's more obvious what things depend on. There's still some coupling I'd like to fix between mode_s.c and station.h and the global variable. I also need to test this PR actually solves issues I ran into, but posting to seek feedback on the approach so far

The end goal is to build `libreadsb.a` so applications can decode messages without having to reimplement it for every language out there

### CODE REVIEW

**Comment by wiseman** [comment]
I love this. Creating a good reusable library could be one of the biggest, most important advances in this domain in *years*. There's a lot of fragmented effort and work that has to be duplicated by multiple people, multiple times that this could avoid.

**Comment by afk11** [comment]
Thanks @wiseman. I can imagine the decode functions are useful to a lot of people, and enabling language bindings is also a big win for this. Kinda funny we know another person porting this library over to rust at the same time..

I just got a function call to decodeModesMessage to work with this branch https://github.com/afk11/airtrack/blob/compile-readsb/demo1090.go

Hopefully this PR is a decent start, or will lead to a discussion about what's required.

**Comment by afk11** [comment]
Oh, also :) A library would be brilliant, because I had this PR prepared initially against `Mictronics/readsb` but realized this is the maintained version now - even though the only difference is in the application layer

Ideally this repo would just submodule in a libreadsb repository or something

**Comment by Niall7459** [comment]
Good work on this look forward to the end result

**Comment by Mictronics** [comment]
Fails to build with any additional build profile enabled.

**Comment by Mictronics** [comment]
You may consider creating your own project/repo for this.

**Comment by afk11** [comment]
I placed some value on doing it here because we'd be dogfooding (using our own code) from the very start, which is a good way to check nothing's going wrong.  I see readsb as a viable open source project (not solely maintained by a company) so I'd hoped we could work together on delivering both together - a library that's a solid foundation for these kind of projects, and the readsb application, with databases and so on.

For my personal purposes this branch works for my project so there isn't much more I actually need here. But I'd love to see this repo depend on a pure library, and so future software can target a library as well. I can make a start and see how far I get - what are your thoughts on this in general?

**Comment by Mictronics** [comment]
>  ...a library that's a solid foundation for these kind of projects, and the readsb application, with databases and so on.

And because of this a library deserves its own project and repo. Taking the existing readsb code as a base, then removing step by step code, which is not needed by a library. e.g. Web application, viewadsb etc.

However, I have no idea how a library should look like.

**Comment by Mictronics** [comment]
@afk11 @wiseman I close this PR in favor for https://github.com/Mictronics/libreadsb
Basic build skeleton exists, needs code :wink:

**Comment by afk11** [comment]
Great news :) Thanks a million, I'll take a look this evening!

**Pull request closed without merging**
